# Generated by Django 5.1.1 on 2024-10-09 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='date_time_of_publication',
        ),
        migrations.RemoveField(
            model_name='like',
            name='text',
        ),
    ]
